# Generated by Django 4.2.3 on 2023-07-27 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ward_local_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localbody',
            options={'verbose_name_plural': 'Local bodies'},
        ),
        migrations.AlterField(
            model_name='ward',
            name='local_body',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.localbody'),
            preserve_default=False,
        ),
    ]
