# Generated by Django 4.2.3 on 2023-07-26 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='location',
        ),
        migrations.AddField(
            model_name='producer',
            name='ward',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='main.ward'),
            preserve_default=False,
        ),
    ]
