# Generated by Django 4.2.3 on 2023-07-28 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_localbody_options_alter_ward_local_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producer',
            old_name='phone_number',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='producer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='producer',
            name='district',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producer',
            name='last_name',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producer',
            name='local_body',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producer',
            name='litre_to_sell',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='milk_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.animaltype'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='rate_per_litre',
            field=models.IntegerField(blank=True, help_text='In rupees', null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='none', max_length=60),
        ),
        migrations.AlterField(
            model_name='producer',
            name='ward',
            field=models.IntegerField(),
        ),
    ]
