# Generated by Django 4.2.3 on 2023-07-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_phone_number_producer_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='google_map_location',
            field=models.URLField(blank=True, null=True),
        ),
    ]
