# Generated by Django 4.2.3 on 2023-07-28 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_producer_google_map_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='milk_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.animal'),
        ),
    ]
