# Generated by Django 4.2.3 on 2023-07-26 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_animal_animaltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='milk_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.animaltype'),
        ),
        migrations.DeleteModel(
            name='MilkSource',
        ),
    ]
