# Generated by Django 4.2.3 on 2023-07-28 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_producer_milk_source'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnimalType',
        ),
    ]
