# Generated by Django 4.2.3 on 2023-07-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_producer_litre_to_sell_producer_rate_per_litre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=60),
        ),
    ]
