# Generated by Django 4.2.3 on 2023-07-29 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_animaltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('contact_number', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=100)),
                ('local_body', models.CharField(max_length=100)),
                ('ward', models.IntegerField()),
                ('google_map_location', models.URLField(blank=True, null=True)),
                ('house_photo', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('litre_to_sell', models.IntegerField(blank=True, null=True)),
                ('rate_per_litre', models.IntegerField(blank=True, help_text='In rupees', null=True)),
                ('trade_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=20)),
                ('status', models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='none', max_length=60)),
                ('milk_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.animal')),
            ],
        ),
        migrations.DeleteModel(
            name='Producer',
        ),
    ]
